getwd()
setwd("/Users/agilesense/gocode/src/github.com/rafidude/100DaysOfCode/33day")
vehicles <- read.csv(unz("vehicles.csv.zip", "vehicles.csv"), stringsAsFactors = F)
head(vehicles)
nrow(vehicles)
ncol(vehicles)
names(vehicles)
head(vehicles[c("mpgData", "make", "model")])
unique(vehicles[,"year"])
table(vehicles$fuelType1)
vehicles$trany <- as.factor(vehicles$trany)
