getwd()
setwd("/Users/agilesense/gocode/src/github.com/rafidude/100DaysOfCode/34day")
uciCar <- read.table('cars.data.csv',sep=',', header=T)
head(uciCar)
class(uciCar)
summary(uciCar)
dim(uciCar)
d <- read.table(paste('http://archive.ics.uci.edu/ml/', 'machine-learning-databases/statlog/german/german.data',sep=''), stringsAsFactors=F,header=F)
print(d[1:3,])
colnames(d) <- c('Status.of.existing.checking.account', 'Duration.in.month', 'Credit.history', 'Purpose', 'Credit.amount', 'Savings account/bonds', 'Present.employment.since', 'Installment.rate.in.percentage.of.disposable.income', 'Personal.status.and.sex', 'Other.debtors/guarantors', 'Present.residence.since', 'Property', 'Age.in.years', 'Other.installment.plans', 'Housing', 'Number.of.existing.credits.at.this.bank', 'Job', 'Number.of.people.being.liable.to.provide.maintenance.for', 'Telephone', 'foreign.worker', 'Good.Loan')
d$Good.Loan <- as.factor(ifelse(d$Good.Loan==1,'GoodLoan','BadLoan'))
print(d[1:3,])
